#!/usr/bin/env bash
set -euo pipefail

# Check required environment variables
REQUIRED_VARS=(
    DIR_EXAMPLES
    AZURE_SERVICE_PRINCIPAL_ID
    AZURE_SERVICE_PRINCIPAL_KEY_PATH
    AZURE_TENANT_ID
    GIT_REPO_USER
    GIT_REPO_TOKEN
    GIT_REPO_URL
)

for var in "${REQUIRED_VARS[@]}"; do
    if [[ -z "${!var:-}" ]]; then
        echo "Error: Environment variable '$var' is not set."
        exit 1
    fi
done

# Check required files
if [[ ! -f "${AZURE_SERVICE_PRINCIPAL_KEY_PATH}" ]]; then
    echo "Error: File '${AZURE_SERVICE_PRINCIPAL_KEY_PATH}' does not exist."
    exit 1
fi

mkdir -p ${DIR_EXAMPLES}/secrets
rm ${DIR_EXAMPLES}/secrets/* 2>/dev/null || true
sed \
    -e s/AZURE_SERVICE_PRINCIPAL_ID/$(echo -n $AZURE_SERVICE_PRINCIPAL_ID | base64)/ \
    -e s/AZURE_SERVICE_PRINCIPAL_KEY/$(cat ${AZURE_SERVICE_PRINCIPAL_KEY_PATH} | base64 )/ \
    -e s/AZURE_TENANT_ID/$(echo $AZURE_TENANT_ID | base64)/ \
    ${DIR_EXAMPLES}/secrets.template/promise-secret.yaml > ${DIR_EXAMPLES}/secrets/promise-secret.yaml

sed \
    -e "s/GIT_REPO_USER/$GIT_REPO_USER/" \
    -e "s/GIT_REPO_TOKEN/$GIT_REPO_TOKEN/" \
    ${DIR_EXAMPLES}/secrets.template/gitrepository-secret.yaml > ${DIR_EXAMPLES}/secrets/gitrepository-secret.yaml

sed \
    -e "s/GIT_REPO_USER/$GIT_REPO_USER/" \
    -e "s/GIT_REPO_TOKEN/$GIT_REPO_TOKEN/" \
    ${DIR_EXAMPLES}/secrets.template/gitstatestore-secret.yaml > ${DIR_EXAMPLES}/secrets/gitstatestore-secret.yaml

sed \
    -e "s^GIT_REPO_URL^$GIT_REPO_URL^" \
    ${DIR_EXAMPLES}/secrets.template/gitrepository.yaml > ${DIR_EXAMPLES}/secrets/gitrepository.yaml

sed \
    -e "s^GIT_REPO_URL^$GIT_REPO_URL^" \
    ${DIR_EXAMPLES}/secrets.template/gitstatestore.yaml > ${DIR_EXAMPLES}/secrets/gitstatestore.yaml

echo """Secrets have been generated and stored in:
    ${DIR_EXAMPLES}/secrets"""
echo "Continue following the instructions in the Readme..."
