apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  creationTimestamp: null
  name: sql
  namespace: default
spec:
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: sql.marketplace.kratix.io
    spec:
      group: marketplace.kratix.io
      names:
        kind: SQL
        plural: sql
        singular: sql
      scope: Namespaced
      versions:
        - name: v1alpha1
          schema:
            openAPIV3Schema:
              properties:
                spec:
                  properties:
                    size:
                      default: small
                      description: |
                        Size of this sql deployment
                      pattern: ^(small|large)$
                      type: string
                  type: object
              type: object
          served: true
          storage: true
  workflows:
    resource:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: instance-configure
            namespace: default
          spec:
            volumes:
            - name: creds
              secret:
                secretName: azure-credentials
                items:
                - key: key
                  path: key.pem
                - key: servicePrincipalID
                  path: service-principal-id
                - key: tenantID
                  path: tenant-id
            containers:
              - image: ghcr.io/syntasso/kratix-marketplace/azure-configure-pipeline:v0.1.0
                name: azure-configure-pipeline
                volumeMounts:
                - name: creds
                  readOnly: true
                  mountPath: "/creds"
      delete:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: instance-delete
            namespace: default
          spec:
            volumes:
            - name: creds
              secret:
                secretName: azure-credentials
                items:
                - key: key
                  path: key.pem
                - key: servicePrincipalID
                  path: service-principal-id
                - key: tenantID
                  path: tenant-id
            containers:
              - image: ghcr.io/syntasso/kratix-marketplace/azure-configure-pipeline:v0.1.0
                name: azure-delete-pipeline
                volumeMounts:
                - name: creds
                  readOnly: true
                  mountPath: "/creds"
status: {}
