#!/usr/bin/env sh

set -euo pipefail

bucketName=$(yq '.status.bucketName' /kratix/input/object.yaml)
url="https://${bucketName}.s3.amazonaws.com"

echo "Waiting for bucket $bucketName to be ready"
while [ "$(curl -s -o /dev/null -w "%{http_code}" "$url")" = "404" ]; do
  echo "."
  sleep 5
done

cat <<EOF > /kratix/metadata/status.yaml
ready: "True"
EOF


