apiVersion: v1
kind: Secret
metadata:
  name: git-secret
  namespace: default
stringData:
  username: <my-username>
  password: <my-password>
---
apiVersion: platform.kratix.io/v1alpha1
kind: GitStateStore
metadata:
  name: tf-repo
spec:
  authMethod: basicAuth
  branch: tf-blog
  secretRef:
    name: git-secret
    namespace: default
  url: https://github.com/<MY ORG>/<MY REPO>.git
---
apiVersion: platform.kratix.io/v1alpha1
kind: Destination
metadata:
  name: tf-blog
  labels:
    environment: hcp
spec:
  strictMatchLabels: true
  filepath:
    mode: none
  stateStoreRef:
    name: tf-repo
    kind: GitStateStore
