apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: s3
spec:
  destinationSelectors:
    - matchLabels:
        environment: hcp
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: buckets.marketplace.kratix.io
    spec:
      group: marketplace.kratix.io
      names:
        kind: bucket
        plural: buckets
        singular: bucket
      scope: Namespaced
      versions:
        - name: v1alpha1
          additionalPrinterColumns:
            - jsonPath: .status.bucketName
              name: "Bucket"
              type: string
            - jsonPath: .status.ready
              name: Ready
              type: string
          schema:
            openAPIV3Schema:
              properties:
                spec:
                  properties:
                    bucketConfig:
                      type: object
                      properties:
                        public:
                          default: false
                          description: |
                            Should the bucket be publicly accessible
                          type: boolean
                  type: object
              type: object
          served: true
          storage: true
  workflows:
    promise:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: modules
            namespace: default
          spec:
            containers:
              - image: ghcr.io/syntasso/kratix-examples/s3-hcp-configure-pipeline:v0.1.0
                name: aws
    resource:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: bucket
            namespace: default
          spec:
            containers:
              - image: ghcr.io/syntasso/kratix-examples/s3-hcp-configure-pipeline:v0.1.0
                name: configure
                env:
                  - name: ORG_NAME
                    value: "example"
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: wait
            namespace: default
          spec:
            containers:
              - image: ghcr.io/syntasso/kratix-examples/s3-hcp-configure-pipeline:v0.1.0
                name: bucket
                command: [ update-status ]
