apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  creationTimestamp: null
  labels:
    kratix.io/promise-version: v0.0.1
  name: s3
spec:
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: s3s.example.syntasso.io
    spec:
      group: example.syntasso.io
      names:
        kind: S3
        plural: s3s
        singular: s3
      scope: Namespaced
      versions:
      - name: v1alpha1
        schema:
          openAPIV3Schema:
            properties:
              spec:
                default: {}
                properties:
                  acceleration_status:
                    description: (Optional) Sets the accelerate configuration of an
                      existing bucket. Can be Enabled or Suspended.
                    type: string
                  access_log_delivery_policy_source_accounts:
                    default: []
                    description: (Optional) List of AWS Account IDs should be allowed
                      to deliver access logs to this bucket.
                    items:
                      type: string
                    type: array
                  access_log_delivery_policy_source_buckets:
                    default: []
                    description: (Optional) List of S3 bucket ARNs which should be
                      allowed to deliver access logs to this bucket.
                    items:
                      type: string
                    type: array
                  access_log_delivery_policy_source_organizations:
                    default: []
                    description: (Optional) List of AWS Organization IDs should be
                      allowed to deliver access logs to this bucket.
                    items:
                      type: string
                    type: array
                  acl:
                    description: (Optional) The canned ACL to apply. Conflicts with
                      `grant`
                    type: string
                  allowed_kms_key_arn:
                    description: The ARN of KMS key which should be allowed in PutObject
                    type: string
                  analytics_self_source_destination:
                    default: false
                    description: Whether or not the analytics source bucket is also
                      the destination bucket.
                    type: boolean
                  analytics_source_account_id:
                    description: The analytics source account id.
                    type: string
                  analytics_source_bucket_arn:
                    description: The analytics source bucket ARN.
                    type: string
                  attach_access_log_delivery_policy:
                    default: false
                    description: Controls if S3 bucket should have S3 access log delivery
                      policy attached
                    type: boolean
                  attach_analytics_destination_policy:
                    default: false
                    description: Controls if S3 bucket should have bucket analytics
                      destination policy attached.
                    type: boolean
                  attach_cloudtrail_log_delivery_policy:
                    default: false
                    description: Controls if S3 bucket should have CloudTrail log
                      delivery policy attached
                    type: boolean
                  attach_deny_incorrect_encryption_headers:
                    default: false
                    description: Controls if S3 bucket should deny incorrect encryption
                      headers policy attached.
                    type: boolean
                  attach_deny_incorrect_kms_key_sse:
                    default: false
                    description: Controls if S3 bucket policy should deny usage of
                      incorrect KMS key SSE.
                    type: boolean
                  attach_deny_insecure_transport_policy:
                    default: false
                    description: Controls if S3 bucket should have deny non-SSL transport
                      policy attached
                    type: boolean
                  attach_deny_ssec_encrypted_object_uploads:
                    default: false
                    description: Controls if S3 bucket should deny SSEC encrypted
                      object uploads.
                    type: boolean
                  attach_deny_unencrypted_object_uploads:
                    default: false
                    description: Controls if S3 bucket should deny unencrypted object
                      uploads policy attached.
                    type: boolean
                  attach_elb_log_delivery_policy:
                    default: false
                    description: Controls if S3 bucket should have ELB log delivery
                      policy attached
                    type: boolean
                  attach_inventory_destination_policy:
                    default: false
                    description: Controls if S3 bucket should have bucket inventory
                      destination policy attached.
                    type: boolean
                  attach_lb_log_delivery_policy:
                    default: false
                    description: Controls if S3 bucket should have ALB/NLB log delivery
                      policy attached
                    type: boolean
                  attach_policy:
                    default: false
                    description: Controls if S3 bucket should have bucket policy attached
                      (set to `true` to use value of `policy` as bucket policy)
                    type: boolean
                  attach_public_policy:
                    default: true
                    description: Controls if a user defined public bucket policy will
                      be attached (set to `false` to allow upstream to apply defaults
                      to the bucket)
                    type: boolean
                  attach_require_latest_tls_policy:
                    default: false
                    description: Controls if S3 bucket should require the latest version
                      of TLS
                    type: boolean
                  attach_waf_log_delivery_policy:
                    default: false
                    description: Controls if S3 bucket should have WAF log delivery
                      policy attached
                    type: boolean
                  availability_zone_id:
                    description: Availability Zone ID or Local Zone ID
                    type: string
                  block_public_acls:
                    default: true
                    description: Whether Amazon S3 should block public ACLs for this
                      bucket.
                    type: boolean
                  block_public_policy:
                    default: true
                    description: Whether Amazon S3 should block public bucket policies
                      for this bucket.
                    type: boolean
                  bucket:
                    description: (Optional, Forces new resource) The name of the bucket.
                      If omitted, Terraform will assign a random, unique name.
                    type: string
                  bucket_prefix:
                    description: (Optional, Forces new resource) Creates a unique
                      bucket name beginning with the specified prefix. Conflicts with
                      bucket.
                    type: string
                  control_object_ownership:
                    default: false
                    description: Whether to manage S3 Bucket Ownership Controls on
                      this bucket.
                    type: boolean
                  create_bucket:
                    default: true
                    description: Controls if S3 bucket should be created
                    type: boolean
                  create_metadata_configuration:
                    default: false
                    description: Whether to create metadata configuration resource
                    type: boolean
                  data_redundancy:
                    description: 'Data redundancy. Valid values: `SingleAvailabilityZone`'
                    type: string
                  expected_bucket_owner:
                    description: The account ID of the expected bucket owner
                    type: string
                  force_destroy:
                    default: false
                    description: (Optional, Default:false ) A boolean that indicates
                      all objects should be deleted from the bucket so that the bucket
                      can be destroyed without error. These objects are not recoverable.
                    type: boolean
                  ignore_public_acls:
                    default: true
                    description: Whether Amazon S3 should ignore public ACLs for this
                      bucket.
                    type: boolean
                  inventory_self_source_destination:
                    default: false
                    description: Whether or not the inventory source bucket is also
                      the destination bucket.
                    type: boolean
                  inventory_source_account_id:
                    description: The inventory source account id.
                    type: string
                  inventory_source_bucket_arn:
                    description: The inventory source bucket ARN.
                    type: string
                  is_directory_bucket:
                    default: false
                    description: If the s3 bucket created is a directory bucket
                    type: boolean
                  lb_log_delivery_policy_source_organizations:
                    default: []
                    description: (Optional) List of AWS Organization IDs should be
                      allowed to deliver ALB/NLB logs to this bucket.
                    items:
                      type: string
                    type: array
                  location_type:
                    description: 'Location type. Valid values: `AvailabilityZone`
                      or `LocalZone`'
                    type: string
                  metadata_inventory_table_configuration_state:
                    description: 'Configuration state of the inventory table, indicating
                      whether the inventory table is enabled or disabled. Valid values:
                      ENABLED, DISABLED'
                    type: string
                  metadata_journal_table_record_expiration:
                    description: 'Whether journal table record expiration is enabled
                      or disabled. Valid values: ENABLED, DISABLED'
                    type: string
                  metadata_journal_table_record_expiration_days:
                    description: Number of days to retain journal table records
                    type: number
                  object_lock_enabled:
                    default: false
                    description: Whether S3 bucket should have an Object Lock configuration
                      enabled.
                    type: boolean
                  object_ownership:
                    default: BucketOwnerEnforced
                    description: 'Object ownership. Valid values: BucketOwnerEnforced,
                      BucketOwnerPreferred or ObjectWriter. ''BucketOwnerEnforced'':
                      ACLs are disabled, and the bucket owner automatically owns and
                      has full control over every object in the bucket. ''BucketOwnerPreferred'':
                      Objects uploaded to the bucket change ownership to the bucket
                      owner if the objects are uploaded with the bucket-owner-full-control
                      canned ACL. ''ObjectWriter'': The uploading account will own
                      the object if the object is uploaded with the bucket-owner-full-control
                      canned ACL.'
                    type: string
                  owner:
                    additionalProperties:
                      type: string
                    default: {}
                    description: Bucket owner's display name and ID. Conflicts with
                      `acl`
                    type: object
                  policy:
                    description: (Optional) A valid bucket policy JSON document. Note
                      that if the policy document is not specific enough (but still
                      valid), Terraform may view the policy as constantly changing
                      in a terraform plan. In this case, please make sure you use
                      the verbose/specific version of the policy. For more information
                      about building AWS IAM policy documents with Terraform, see
                      the AWS IAM Policy Document Guide.
                    type: string
                  putin_khuylo:
                    default: true
                    description: 'Do you agree that Putin doesn''t respect Ukrainian
                      sovereignty and territorial integrity? More info: https://en.wikipedia.org/wiki/Putin_khuylo!'
                    type: boolean
                  region:
                    description: Region where the resource(s) will be managed. Defaults
                      to the region set in the provider configuration
                    type: string
                  request_payer:
                    description: (Optional) Specifies who should bear the cost of
                      Amazon S3 data transfer. Can be either BucketOwner or Requester.
                      By default, the owner of the S3 bucket would incur the costs
                      of any data transfer. See Requester Pays Buckets developer guide
                      for more information.
                    type: string
                  restrict_public_buckets:
                    default: true
                    description: Whether Amazon S3 should restrict public bucket policies
                      for this bucket.
                    type: boolean
                  skip_destroy_public_access_block:
                    default: true
                    description: Whether to skip destroying the S3 Bucket Public Access
                      Block configuration when destroying the bucket. Only used if
                      `public_access_block` is set to true.
                    type: boolean
                  tags:
                    additionalProperties:
                      type: string
                    default: {}
                    description: (Optional) A mapping of tags to assign to the bucket.
                    type: object
                  transition_default_minimum_object_size:
                    description: 'The default minimum object size behavior applied
                      to the lifecycle configuration. Valid values: all_storage_classes_128K
                      (default), varies_by_storage_class'
                    type: string
                  type:
                    default: Directory
                    description: 'Bucket type. Valid values: `Directory`'
                    type: string
                  versioning:
                    additionalProperties:
                      type: string
                    default: {}
                    description: Map containing versioning configuration.
                    type: object
                type: object
            type: object
        served: true
        storage: true
  destinationSelectors:
  - matchLabels:
      environment: terraform
  workflows:
    config: {}
    promise:
      configure:
      - apiVersion: platform.kratix.io/v1alpha1
        kind: Pipeline
        metadata:
          name: dependencies
        spec:
          containers:
          - image: kratix-workshop/s3-promise-pipeline:v0.1.0
            name: configure-deps
    resource:
      configure:
      - apiVersion: platform.kratix.io/v1alpha1
        kind: Pipeline
        metadata:
          name: instance-configure
        spec:
          containers:
          - env:
            - name: MODULE_SOURCE
              value: git::https://github.com/terraform-aws-modules/terraform-aws-s3-bucket.git?ref=v5.10.0
            image: ghcr.io/syntasso/kratix-cli/terraform-generate:v0.4.0
            name: terraform-generate
status:
  workflows: 0
  workflowsFailed: 0
  workflowsSucceeded: 0
